feat: a simple approach to allow keyboard navigation for menu items
patternfly-yew/patternfly-yew pull request #102
Opened 2023-12-05 17:17 UTC by ctron

Also: provide some helpers to work with HTML stuff

2023-12-05 19:15 UTC, aDogCalledSpot requested changes
Really cool stuff! Only have some really minor stylistic things in the review.

Could this be extracted to a utilities file? This can be used for things other than menus as well (DualListSelector is the first one that comes to mind).

It will probably end up being exactly the same thing as [patternfly-react's keyboard handler](https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/helpers/KeyboardHandler.tsx).

2023-12-05 19:15 UTC, aDogCalledSpot commented on src/components/menu/mod.rs
> +            .and_then(|ele| ele.dyn_into::<HtmlElement>().ok());
let Some else should be nicer here

2023-12-05 19:15 UTC, aDogCalledSpot commented on src/utils/html.rs
> +        }
`self.cast::<Element>().is_some_and(|element| element.contains(target))`

2023-12-06 07:20 UTC, ctron commented on src/components/menu/mod.rs
> +        .and_then(|element| element.dyn_into::<HtmlElement>().ok())
Yea, I forgot rust can do that! :grin:

2023-12-06 08:56 UTC, aDogCalledSpot approved these changes

2023-12-06 09:03 UTC, merged