refactor: Remove unnecessary single-dependency feature
patternfly-yew/patternfly-yew pull request #143
Opened 2024-04-16 11:52 UTC by kate-shine

BREAKING CHANGE: Build will fail for users who explicitly enabled the "router" feature

Having single dependency feature aliased with a different alias is unnecessary. If there is a need to add more dependencies, it's easy to re-add alias with the same name :)

2024-04-16 11:57 UTC, ctron requested changes
https://github.com/patternfly-yew/patternfly-yew/blob/72a65dda60d493a91286fee38d75b044de741081/src/components/breadcrumb/mod.rs#L8-L13

I think those two need to be changed too.

2024-04-16 13:52 UTC, kate-shine commented
Oh, interesting, I thought that any misses would be caught by test build.

2024-04-16 16:21 UTC, ctron approved these changes

2024-04-23 11:39 UTC, ctron approved these changes

2024-04-23 11:39 UTC, merged